/**
 * Retrieves the translation of text.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-i18n/
 */
import { __ } from '@wordpress/i18n';

/**
 * React hook that is used to mark the block wrapper element.
 * It provides all the necessary props like the class name.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/packages/packages-block-editor/#useblockprops
 */
import { useBlockProps } from '@wordpress/block-editor';
import { TextControl } from '@wordpress/components';

/**
 * Lets webpack process CSS, SASS or SCSS files referenced in JavaScript files.
 * Those files can contain any CSS code that gets applied to the editor.
 *
 * @see https://www.npmjs.com/package/@wordpress/scripts#using-css
 */
import './editor.scss';

/**
 * The edit function describes the structure of your block in the context of the
 * editor. This represents what the editor will render when the block is used.
 *
 * @see https://developer.wordpress.org/block-editor/reference-guides/block-api/block-edit-save/#edit
 *
 * @return {WPElement} Element to render.
 */
export default function Edit({ attributes, setAttributes }) {
	// either props or css for sizing

	let aspectRatio = "";
	let aspectRatioUrl = "";
	if(attributes.aspectRatio = "4-3") {
		aspectRatio = "4 / 3";
		aspectRatioUrl = "1.3333333333333333";
	} else if(attributes.aspectRatio = "16-9") {
		aspectRatio = "16 / 9";
		aspectRatioUrl = "1.7777777777777777";
	}
	const css = aspectRatio ? "aspect-ratio: " + aspectRatio + ";width: 100%;" : "";
	const styleAttr = `style="${css}"`;
	const sizeAttr = aspectRatio ? "" : `width="${attributes.width}px" height="${attributes.height}"`;
	const authkey = ""
	const resid = "";
	const em = "2";
	const src = `https://onedrive.live.com/embed?resid=${resid}&amp;authkey=${resid}&amp;em=${em}` +
		aspectRatioUrl ? `&amp;wdAr=${aspectRatioUrl}` : ``;
	return (
		<iframe 
			{ ...src }
			{ ...sizeAttr }
			frameborder="0"
			{ ...useBlockProps() }
		>
			This is an embedded 
			<a target="_blank" href="https://office.com" rel="noopener">Microsoft Office</a> 
			presentation, powered by 
			<a target="_blank" href="https://office.com/webapps" rel="noopener">Office</a>. 
			Generated by MSODPP Block for WordPress.
		</iframe>
	);
}
